[package]
name = "constant-binary-search"
version = "0.1.0"
edition = "2024"

[profile.release]
debug = true

[dependencies]
rand = "0.9.2"
rdst = "0.20.14"
static-search-tree = { version = "0.1.0", path = "../eth/git/sa-searching/static-search-tree" }
